spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:h2:file:./data/gallery-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.frontend-url=http://localhost:4200

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:replace-with-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:replace-with-google-client-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

